name: Build, Push, Ssh, Pull, Down, Up

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install esbuild
        run: npm install -D esbuild

      - name: Build client project
        run: |
          cd client
          npm install --legacy-peer-deps
          npm run build

      - name: Set up backend server
        run: |
          cd server
          npm install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: bsignbkc/cinemax-server:staging

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: bsignbkc/cinemax-client:staging

  # pull-and-up:
  #   name: Pull new image and re run with the new version
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #     - uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_KEY }}
  #         script: |
  #           cd ${{ secrets.PATH }}
  #           docker-compose pull && docker-compose down && docker-compose up -d
